name: Execute python script to create github issue

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout actions
        uses: actions/checkout@v1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Create github issue
        env:
          GITHUB_TOKEN: ${{ secrets.GRIDEA }}
        run: |
          GITHUB_TOKEN=${GITHUB_TOKEN} python scripts/raiseIssue.py
